language: php
sudo: false

cache:
    directories:
      - $HOME/.composer/cache

php: 
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    #phpspec cant handle 7.0 yet
    php: 7

before_script:
  - composer self-update
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then rm phpspec.yml.dist; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require --no-update --dev henrikbjorn/phpspec-code-coverage; fi;'
  - composer update
after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

script: vendor/bin/phpspec run -fpretty -v
